### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by blewisio** [blewisio/rainforest-ui#1]
Due to a [limitation of rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss/issues/336), we're manually copying over `.css` files in a post-build step: This works fine, but we are lacking a minify step since the postcss plugin is essentially a no-op.

**Comment by muhammadjufry** [comment]
I think I can do this
Can you assign this issue to me, please?

**Comment by blewisio** [comment]
Added in eedcdb9
